/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto02;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Newshore
 */
public class ViewAtender extends javax.swing.JFrame {
   
    public ViewAtender() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        jMedicamentos = new javax.swing.JRadioButton();
        jCitas = new javax.swing.JRadioButton();
        labelCedula = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        separadorCedula = new javax.swing.JSeparator();
        labelCajero = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        separadorCajero = new javax.swing.JSeparator();
        BtnAtender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto02/img/image (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 420));

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atiende Un Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        BtnVolver.setBackground(new java.awt.Color(73, 181, 172));
        BtnVolver.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("x");
        BtnVolver.setBorder(null);
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 34));

        jMedicamentos.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jMedicamentos);
        jMedicamentos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        jMedicamentos.setSelected(true);
        jMedicamentos.setText("Medicamentos");
        jMedicamentos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMedicamentosStateChanged(evt);
            }
        });
        jMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicamentosActionPerformed(evt);
            }
        });
        jPanel2.add(jMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jCitas.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jCitas);
        jCitas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jCitas.setForeground(new java.awt.Color(255, 255, 255));
        jCitas.setText("Citas");
        jCitas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCitasStateChanged(evt);
            }
        });
        jPanel2.add(jCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, -1));

        labelCedula.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        labelCedula.setForeground(new java.awt.Color(255, 255, 255));
        labelCedula.setText("Cedula Del Usuario");
        jPanel2.add(labelCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        txtCedula.setBackground(new java.awt.Color(33, 45, 62));
        txtCedula.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCedula.setForeground(new java.awt.Color(255, 255, 255));
        txtCedula.setBorder(null);
        txtCedula.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        separadorCedula.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(separadorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 7));

        labelCajero.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        labelCajero.setForeground(new java.awt.Color(255, 255, 255));
        labelCajero.setText("Nombre Del Cajero");
        jPanel2.add(labelCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        txtNombre.setBackground(new java.awt.Color(33, 45, 62));
        txtNombre.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, -1));

        separadorCajero.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(separadorCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, 10));

        BtnAtender.setBackground(new java.awt.Color(73, 181, 172));
        BtnAtender.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnAtender.setForeground(new java.awt.Color(255, 255, 255));
        BtnAtender.setText("ATENDER");
        BtnAtender.setBorder(null);
        BtnAtender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtenderActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAtender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 99, 34));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 400, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        ViewPrincipal open = new ViewPrincipal();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void BtnAtenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtenderActionPerformed

       

    }//GEN-LAST:event_BtnAtenderActionPerformed

    private void jMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicamentosActionPerformed
       
    }//GEN-LAST:event_jMedicamentosActionPerformed

    private void jMedicamentosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMedicamentosStateChanged
         if (jMedicamentos.isSelected()) {
                labelCajero.setVisible(false);
                labelCedula.setVisible(true);
                txtCedula.setVisible(true);
                txtNombre.setVisible(false);
                separadorCajero.setVisible(false);
                separadorCedula.setVisible(true);
            }
    }//GEN-LAST:event_jMedicamentosStateChanged

    private void jCitasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCitasStateChanged
        if(jCitas.isSelected()) {
                labelCajero.setVisible(true);
                labelCedula.setVisible(false);
                txtCedula.setVisible(false);
                txtNombre.setVisible(true);
                separadorCajero.setVisible(true);
                separadorCedula.setVisible(false);
            }
    }//GEN-LAST:event_jCitasStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewAtender.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAtender().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtender;
    private javax.swing.JButton BtnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jMedicamentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCajero;
    private javax.swing.JLabel labelCedula;
    private javax.swing.JSeparator separadorCajero;
    private javax.swing.JSeparator separadorCedula;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
