/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto02;

import javax.swing.JOptionPane;

/**
 *
 * @author Newshore
 */
public class ViewAtender extends javax.swing.JFrame {
   
    public ViewAtender(String nombreEmpleado,String nombreCajero,String cedulaCliente, Cola<Cliente> listClientes,String Medicamentos) {
        initComponents();

        txtNombreEmpleado.setText(nombreEmpleado);
        txtNombreCajero.setText(nombreCajero);
        txtCedulaCliente.setText(cedulaCliente);
        txtMedicamentos.setText(Medicamentos);

        labelCitas.setVisible(false);
        labelCajero.setVisible(true);
        labelEmpleado.setVisible(false);
        txtCedulaCliente.setVisible(true);
        txtNombreCajero.setVisible(true);
        txtNombreEmpleado.setVisible(false);
        txtMedicamentos.setVisible(true);
        txtCitas.setVisible(false);
        separadorCajero.setVisible(true);
        separadorCedula.setVisible(true);

        BtnAtenderCitas.setVisible(false);
        BtnAtenderMedicamentos.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BtnVolver = new javax.swing.JButton();
        jMedicamentos = new javax.swing.JRadioButton();
        jCitas = new javax.swing.JRadioButton();
        txtCedulaCliente = new javax.swing.JTextField();
        separadorCedula = new javax.swing.JSeparator();
        labelCajero = new javax.swing.JLabel();
        txtNombreCajero = new javax.swing.JTextField();
        separadorCajero = new javax.swing.JSeparator();
        BtnAtenderMedicamentos = new javax.swing.JButton();
        txtNombreEmpleado = new javax.swing.JTextField();
        separadorCajero1 = new javax.swing.JSeparator();
        labelEmpleado = new javax.swing.JLabel();
        labelCedula1 = new javax.swing.JLabel();
        labelCitas = new javax.swing.JLabel();
        BtnAtenderCitas = new javax.swing.JButton();
        txtMedicamentos = new javax.swing.JTextArea();
        txtCitas = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel1.setPreferredSize(new java.awt.Dimension(370, 470));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto02/img/image (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 530));

        jPanel2.setBackground(new java.awt.Color(33, 45, 62));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Atiende Un Usuario");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        BtnVolver.setBackground(new java.awt.Color(73, 181, 172));
        BtnVolver.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(255, 255, 255));
        BtnVolver.setText("x");
        BtnVolver.setBorder(null);
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(BtnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 30, 34));

        jMedicamentos.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jMedicamentos);
        jMedicamentos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        jMedicamentos.setSelected(true);
        jMedicamentos.setText("Medicamentos");
        jMedicamentos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMedicamentosStateChanged(evt);
            }
        });
        jMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMedicamentosActionPerformed(evt);
            }
        });
        jPanel2.add(jMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jCitas.setBackground(new java.awt.Color(33, 45, 62));
        buttonGroup1.add(jCitas);
        jCitas.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 11)); // NOI18N
        jCitas.setForeground(new java.awt.Color(255, 255, 255));
        jCitas.setText("Citas");
        jCitas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCitasStateChanged(evt);
            }
        });
        jPanel2.add(jCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 70, -1));

        txtCedulaCliente.setBackground(new java.awt.Color(33, 45, 62));
        txtCedulaCliente.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtCedulaCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCedulaCliente.setBorder(null);
        txtCedulaCliente.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel2.add(txtCedulaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, -1));

        separadorCedula.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(separadorCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 150, 7));

        labelCajero.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        labelCajero.setForeground(new java.awt.Color(255, 255, 255));
        labelCajero.setText("Nombre Del Cajero");
        jPanel2.add(labelCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        txtNombreCajero.setBackground(new java.awt.Color(33, 45, 62));
        txtNombreCajero.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNombreCajero.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreCajero.setBorder(null);
        txtNombreCajero.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombreCajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCajeroActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, -1));

        separadorCajero.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(separadorCajero, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, 10));

        BtnAtenderMedicamentos.setBackground(new java.awt.Color(73, 181, 172));
        BtnAtenderMedicamentos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnAtenderMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        BtnAtenderMedicamentos.setText("ATENDER MEDICAMENTOS");
        BtnAtenderMedicamentos.setBorder(null);
        BtnAtenderMedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtenderMedicamentosActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAtenderMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 190, 34));

        txtNombreEmpleado.setBackground(new java.awt.Color(33, 45, 62));
        txtNombreEmpleado.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        txtNombreEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreEmpleado.setBorder(null);
        txtNombreEmpleado.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombreEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmpleadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombreEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 150, -1));

        separadorCajero1.setBackground(new java.awt.Color(73, 181, 172));
        jPanel2.add(separadorCajero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 150, 10));

        labelEmpleado.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        labelEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        labelEmpleado.setText("Nombre Del Doctor");
        jPanel2.add(labelEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        labelCedula1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        labelCedula1.setForeground(new java.awt.Color(255, 255, 255));
        labelCedula1.setText("Cedula Del Usuario");
        jPanel2.add(labelCedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        labelCitas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        labelCitas.setForeground(new java.awt.Color(255, 255, 255));
        labelCitas.setText("Ingrese los sintomas:");
        jPanel2.add(labelCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, -1, -1));

        BtnAtenderCitas.setBackground(new java.awt.Color(73, 181, 172));
        BtnAtenderCitas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        BtnAtenderCitas.setForeground(new java.awt.Color(255, 255, 255));
        BtnAtenderCitas.setText("ATENDER CITAS");
        BtnAtenderCitas.setBorder(null);
        BtnAtenderCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtenderCitasActionPerformed(evt);
            }
        });
        jPanel2.add(BtnAtenderCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 190, 34));

        txtMedicamentos.setBackground(new java.awt.Color(73, 181, 172));
        txtMedicamentos.setColumns(20);
        txtMedicamentos.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 13)); // NOI18N
        txtMedicamentos.setForeground(new java.awt.Color(255, 255, 255));
        txtMedicamentos.setRows(5);
        txtMedicamentos.setBorder(null);
        jPanel2.add(txtMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 260, 100));

        txtCitas.setBackground(new java.awt.Color(73, 181, 172));
        txtCitas.setColumns(20);
        txtCitas.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 13)); // NOI18N
        txtCitas.setForeground(new java.awt.Color(255, 255, 255));
        txtCitas.setRows(5);
        jPanel2.add(txtCitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, 260, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 400, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        ViewPrincipal open = new ViewPrincipal();
        open.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void txtNombreCajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreCajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCajeroActionPerformed

    private void BtnAtenderMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtenderMedicamentosActionPerformed
                     
       // if(txtNombreCajero.equals())
        ViewCliente.listaCliente.DesencolarM();
        JOptionPane.showMessageDialog(this, "Los medicamentos fueron despachados de forma correcta");


    }//GEN-LAST:event_BtnAtenderMedicamentosActionPerformed

    private void jMedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMedicamentosActionPerformed

    }//GEN-LAST:event_jMedicamentosActionPerformed

    private void jMedicamentosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMedicamentosStateChanged
        if (jMedicamentos.isSelected()) {
            labelCitas.setVisible(false);
            labelCajero.setVisible(true);
            labelEmpleado.setVisible(false);
            txtMedicamentos.setVisible(true);
            txtCitas.setVisible(false);
            txtCedulaCliente.setVisible(true);
            txtNombreCajero.setVisible(true);
            txtNombreEmpleado.setVisible(false);
            separadorCajero.setVisible(false);
            separadorCedula.setVisible(true);
            BtnAtenderCitas.setVisible(false);
            BtnAtenderMedicamentos.setVisible(true);
        }
    }//GEN-LAST:event_jMedicamentosStateChanged

    private void jCitasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCitasStateChanged
        if (jCitas.isSelected()) {
            labelCitas.setVisible(true);
            labelCajero.setVisible(false);
            labelEmpleado.setVisible(true);
            txtCitas.setVisible(true);
            txtMedicamentos.setVisible(false);
            txtCedulaCliente.setVisible(true);
            txtNombreCajero.setVisible(false);
            txtNombreEmpleado.setVisible(true);
            separadorCajero.setVisible(true);
            BtnAtenderCitas.setVisible(true);
            BtnAtenderMedicamentos.setVisible(false);

        }
    }//GEN-LAST:event_jCitasStateChanged

    private void txtNombreEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmpleadoActionPerformed
       
    }//GEN-LAST:event_txtNombreEmpleadoActionPerformed

    private void BtnAtenderCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtenderCitasActionPerformed
       
        ViewCliente.listaCliente.Desencolar();
        JOptionPane.showMessageDialog(this, "La cita fueron despachados de forma correcta");
    }//GEN-LAST:event_BtnAtenderCitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewAtender("","","",ViewCliente.listaCliente,"").setVisible(true);                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtenderCitas;
    private javax.swing.JButton BtnAtenderMedicamentos;
    private javax.swing.JButton BtnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jCitas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jMedicamentos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelCajero;
    private javax.swing.JLabel labelCedula1;
    private javax.swing.JLabel labelCitas;
    private javax.swing.JLabel labelEmpleado;
    private javax.swing.JSeparator separadorCajero;
    private javax.swing.JSeparator separadorCajero1;
    private javax.swing.JSeparator separadorCedula;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextArea txtCitas;
    private javax.swing.JTextArea txtMedicamentos;
    private javax.swing.JTextField txtNombreCajero;
    private javax.swing.JTextField txtNombreEmpleado;
    // End of variables declaration//GEN-END:variables
}
